--  교재 P26



SELECT * FROM EMP; 
DESC DEPT;
SELECT EMPNO, ENAME FROM EMP;

SELECT * FROM DEPT;

SELECT DNAME , ',it''s deptno: ' , DEPTNO "DNAME AND DEPTNO" 
FROM DEPT;

SELECT DNAME, q'[ it's deptno : ]', deptno "DNAME AND DEPTNO" FROM DEPT;

SELECT DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP;

SELECT JOB, ENAME FROM EMP ORDER BY 1,2;
SELECT DISTINCT JOB, ENAME FROM EMP ORDER BY 1,2; 

SELECT ENAME || JOB FROM EMP;
SELECT ENAME ||'-'||JOB FROM EMP;
SELECT ENAME ||' ''s job is '|| job "NAME AND JOB" FROM EMP;

SELECT * FROM EMP;
SELECT ENAME || '(' || JOB || '), ' || ENAME || '''' || JOB || '''' AS "NAME AND JOB"
FROM EMP;

SELECT EMPNO, ENAME FROM EMP WHERE EMPNO = 7900;

SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME = 'SMITH';

// 날짜 조회 할 때 '' 작은따옴표 사용 
select EMPNO, ENAME, SAL FROM EMP WHERE HIREDATE = '80/12/17';

SELECT ENAME, SAL,SAL+100 FROM EMP WHERE DEPTNO =10;

SELECT ENAME, HIREDATE FROM EMP;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE >= '81/12/25';


SELECT * FROM PROFESSOR;
SELECT NAME, 'good morning ~~!' "GOOD Morning" from PROFESSOR;
SELECT Profno "Prof's NO", name AS "Prof's NAME", pay Prof_Pay from professor;



